/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HRPR4bdT1jM
 */
import { Button } from "../ui/button"
import { Input } from "../ui/input"
import { Checkbox } from "../ui/checkbox"
import { Textarea } from "../ui/textarea"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "../ui/select"

export function Create_opportunity() {
  return (
    (<div className="max-w-4xl mx-auto p-6">
      <div className="flex items-center justify-between border-b pb-4">
        <Button className="flex items-center space-x-2" variant="ghost">
          <ArrowLeftIcon className="w-4 h-4" />
          <span>Back</span>
        </Button>
        <div className="flex space-x-4 items-center">
          <div className="flex items-center space-x-2">
            <div
              className="rounded-full bg-blue-500 w-5 h-5 flex items-center justify-center text-white">1</div>
            <span className="font-semibold">Basic Details</span>
          </div>
          <ChevronRightIcon className="w-4 h-4" />
          <div className="flex items-center space-x-2">
            <div
              className="rounded-full bg-gray-200 w-5 h-5 flex items-center justify-center text-gray-500">2</div>
            <span>Registration Details</span>
          </div>
        </div>
      </div>
      <div className="mt-6">
        <h1 className="text-2xl font-semibold mb-6">Basic Details</h1>
        <div
          className="border-dashed border-2 border-gray-300 rounded-lg p-6 flex justify-center items-center mb-6">
          <span className="text-gray-400">Opportunity Logo *</span>
        </div>
        <form>
          <div className="grid gap-6">
            <Input placeholder="Name" type="text" />
            <Input placeholder="Registration Deadline" type="date" />
            <Input placeholder="Eligibility" type="text" />
            <Input placeholder="Year of Graduation" type="number" />
            <Input placeholder="Age" type="number" />
            <Input placeholder="Team Members Number" type="number" />
            <div className="flex items-center space-x-4">
              <Checkbox id="inter-year" />
              <label className="text-sm font-medium leading-none" htmlFor="inter-year">
                Inter-year allowed?
              </label>
            </div>
            <div className="flex items-center space-x-4">
              <Checkbox id="inter-college" />
              <label className="text-sm font-medium leading-none" htmlFor="inter-college">
                Inter-college allowed?
              </label>
            </div>
            <Input
              placeholder="Other Team Constraints (e.g., 1 mandatory female)"
              type="text" />
            <Textarea placeholder="Description" />
            <div>
              <label className="block text-sm font-medium mb-1">
                Timeline (Multiple rounds with each round having a. Description b. Upload format c. Results)
              </label>
              <div className="grid gap-4">
                <div>
                  <Textarea className="mb-2" placeholder="Round 1 Description" />
                  <Select>
                    <SelectTrigger id="upload-format">
                      <SelectValue placeholder="Select Upload Format" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectItem value="pdf">PDF</SelectItem>
                      <SelectItem value="doc">DOC</SelectItem>
                      <SelectItem value="jpg">JPG</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Textarea className="mb-2" placeholder="Round 2 Description" />
                  <Select>
                    <SelectTrigger id="upload-format">
                      <SelectValue placeholder="Select Upload Format" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectItem value="pdf">PDF</SelectItem>
                      <SelectItem value="doc">DOC</SelectItem>
                      <SelectItem value="jpg">JPG</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Textarea className="mb-2" placeholder="Round 3 Description" />
                  <Select>
                    <SelectTrigger id="upload-format">
                      <SelectValue placeholder="Select Upload Format" />
                    </SelectTrigger>
                    <SelectContent position="popper">
                      <SelectItem value="pdf">PDF</SelectItem>
                      <SelectItem value="doc">DOC</SelectItem>
                      <SelectItem value="jpg">JPG</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </div>
            <Select>
              <SelectTrigger id="mode">
                <SelectValue placeholder="Mode (online/offline)" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="online">Online</SelectItem>
                <SelectItem value="offline">Offline</SelectItem>
              </SelectContent>
            </Select>
            <Textarea placeholder="Rewards (description)" />
            <Textarea placeholder="FAQs" />
            <Input placeholder="Organizer Contact" type="text" />
            <Button className="mt-4">Next</Button>
          </div>
        </form>
      </div>
    </div>)
  );
}


function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
