// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/y5JZAAB2VFC
//  */
// import { CardContent, Card } from "../ui/card"

// export function Teams() {
//   return (
//     (<div>
//       <div className="w-full max-w-3xl mx-auto grid gap-6">
//         <div className="space-y-2">
//           <div>
//             Teams for
//             <span className="font-semibold">Hackathon</span>
//           </div>
//           <p className="text-sm leading-none">Here are the teams participating in the "Hackathon" event.</p>
//         </div>
//         <div className="space-y-4">
//           <Card>
//             <CardContent className="grid gap-2">
//               <div className="flex flex-row items-center space-x-2">
//                 <UsersIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
//                 <p className="font-semibold">Team Name</p>
//               </div>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Team idea</p>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
//                 Skills Preferred: Design, Development
//               </p>
//             </CardContent>
//             <CardContent className="border-t grid grid-cols-2 items-center">
//               <p className="text-sm">Members</p>
//               <p className="text-sm justify-self-end">5</p>
//               <p className="text-sm">Leader</p>
//               <p className="text-sm justify-self-end">John Doe</p>
//             </CardContent>
//           </Card>
//           <Card>
//             <CardContent className="grid gap-2">
//               <div className="flex flex-row items-center space-x-2">
//                 <UsersIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
//                 <p className="font-semibold">Team Name</p>
//               </div>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Team idea</p>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
//                 Skills Preferred: Marketing, Sales
//               </p>
//             </CardContent>
//             <CardContent className="border-t grid grid-cols-2 items-center">
//               <p className="text-sm">Members</p>
//               <p className="text-sm justify-self-end">3</p>
//               <p className="text-sm">Leader</p>
//               <p className="text-sm justify-self-end">Alice Johnson</p>
//             </CardContent>
//           </Card>
//           <Card>
//             <CardContent className="grid gap-2">
//               <div className="flex flex-row items-center space-x-2">
//                 <UsersIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
//                 <p className="font-semibold">Team Name</p>
//               </div>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">Team idea</p>
//               <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
//                 Skills Preferred: Research, Analysis
//               </p>
//             </CardContent>
//             <CardContent className="border-t grid grid-cols-2 items-center">
//               <p className="text-sm">Members</p>
//               <p className="text-sm justify-self-end">4</p>
//               <p className="text-sm">Leader</p>
//               <p className="text-sm justify-self-end">Ethan Wilson</p>
//             </CardContent>
//           </Card>
//         </div>
//       </div>
//     </div>)
//   );
// }
import { useState } from 'react';
import { CardContent, Card, CardFooter } from '../ui/card';
import { Button } from '../ui/button';

export function Teams() {
  const [teamData] = useState([
    {
      id: 1,
      name: 'Team A',
      idea: 'Team A idea description',
      skills: ['Design', 'Development'],
      members: ['John Doe', 'Jane Smith', 'Alice Johnson'],
      leader: 'John Doe'
    },
    {
      id: 2,
      name: 'Team B',
      idea: 'Team B idea description',
      skills: ['Marketing', 'Sales'],
      members: ['Ethan Wilson', 'Emma Brown'],
      leader: 'Ethan Wilson'
    },
    {
      id: 3,
      name: 'Team C',
      idea: 'Team C idea description',
      skills: ['Research', 'Analysis'],
      members: ['Michael Johnson', 'Sarah Davis', 'David Miller'],
      leader: 'Michael Johnson'
    },
    {
        id: 4,
        name: 'Team 5',
        idea: 'Team d idea description',
        skills: ['Research', 'Analysis'],
        members: ['Michael Johnson', 'Sarah Davis', 'David Miller'],
        leader: 'Michael Johnson'

    }
  ]);

  return (
    <div>
      <div className="w-full max-w-3xl mx-auto grid gap-6">
        <div className="space-y-2">
          <div>
            Teams for
            <span className="font-semibold">Hackathon</span>
          </div>
          <p className="text-sm leading-none">Here are the teams participating in the "Hackathon" event.</p>
        </div>
        <div className="space-y-4">
          {teamData.map(team => (
            <Card key={team.id}>
              <CardContent className="grid gap-2">
                <div className="flex flex-row items-center space-x-2">
                  <UsersIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
                  <p className="font-semibold">{team.name}</p>
                </div>
                <p className="text-sm leading-none text-gray-500 dark:text-gray-400">{team.idea}</p>
                <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                  Skills Preferred: {team.skills.join(', ')}
                </p>
              </CardContent>
              <CardContent className="border-t grid grid-cols-2 items-center">
                <p className="text-sm">Members</p>
                <p className="text-sm justify-self-end">{team.members.length}</p>
                <p className="text-sm">Leader</p>
                <p className="text-sm justify-self-end">{team.leader}</p>
              </CardContent>
              <CardFooter><Button className="bg-gray-300 rounded-md p-2 left-5">Interested</Button></CardFooter>
            </Card>
          ))}
          
        </div>
        
      </div>
    </div>
  );
}



function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
